### ISSUE TITLE
Replace `if` with `where` in `mario_negri_eligible`

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-it#36]
We can only use `if` statements with parameters. For variables, we need vectorized functions like `where` or `select`

**Comment by MaxGhenis** [comment]
We import np.where as where and use that as the convention: https://github.com/PolicyEngine/policyengine-core/blob/e29d51c7bbdcdc5ef672232d54795c361102302f/policyengine_core/model_api.py#L7

**Comment by anth-volk** [comment]
Thanks, I will bear that in mind moving forward
